/***
* Scripts para criaacao e insersao de dados
* Base de Dados do CePES Material 
* Casssio Trindade
* 09/09/2015
***/

USE cepes_e;

-- Tabelas

CREATE TABLE TB_FUNCAO (
  ID_FUNCAO int(11) NOT NULL AUTO_INCREMENT,
  NOME varchar(255) NOT NULL,
  DESCRICAO varchar(255) NOT NULL,
  PRIMARY KEY (ID_FUNCAO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_USUARIO (
  ID_USUARIO int(11) NOT NULL AUTO_INCREMENT,
  USUARIO varchar(30) NOT NULL,
  SENHA varchar(8) NOT NULL,
  ADMINISTRADOR tinyint(1) NOT NULL,
  MATRICULA varchar(11) NOT NULL,
  NOME varchar(120) NOT NULL,
  EMAIL varchar(120) NOT NULL,
  DATA_CADASTRO datetime NOT NULL,
  ID_FUNCAO int(11) NOT NULL,
  CPF varchar(11) NOT NULL,
  PRIMARY KEY (`ID_USUARIO`),
  UNIQUE KEY `MATRICULA_UNIQUE` (`MATRICULA`),
  UNIQUE KEY `CPF_UNIQUE` (`CPF`),
  KEY `fk_TB_FUNCAO_idx` (`ID_FUNCAO`),
  CONSTRAINT `fk_TB_FUNCAO` FOREIGN KEY (`ID_FUNCAO`) REFERENCES `TB_FUNCAO` (`ID_FUNCAO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_PROJETOS (
  ID_PROJETO int(11) NOT NULL AUTO_INCREMENT,
  NOME_PROJETO varchar(120) NOT NULL,
  PROGRAMA varchar(120) NOT NULL,
  ORIGEM varchar(120) NOT NULL,
  DATA_CADASTRO datetime NOT NULL,
  ID_CORDENADOR int(11) NOT NULL,
  PRIMARY KEY (`ID_PROJETO`),
  KEY `FK_ID_CORDENADOR_idx` (`ID_CORDENADOR`),
  CONSTRAINT `FK_ID_CORDENADOR` FOREIGN KEY (`ID_CORDENADOR`) REFERENCES `TB_USUARIO` (`ID_USUARIO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE TB_IDIOMA (
  ID_IDIOMA int(11) NOT NULL AUTO_INCREMENT,
  NOME varchar(120) NOT NULL,
  PAIS varchar(120) NOT NULL,
  PRIMARY KEY (`ID_IDIOMA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

   
CREATE TABLE TB_AUTOR (
  ID_AUTOR int(11) NOT NULL AUTO_INCREMENT,
  NOME varchar(60) NOT NULL,
  SOBRENOME varchar(60) NOT NULL,
  PRIMARY KEY (ID_AUTOR)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_EDITORA (
  ID_EDITORA int(11) NOT NULL AUTO_INCREMENT,
  NOME varchar(255) NOT NULL,
  PRIMARY KEY (ID_EDITORA)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_LIVRO (
  ID_LIVRO int(11) NOT NULL,
  TITULO varchar(120) NOT NULL,
  SUBTITULO varchar(120) NOT NULL,
  DATA_CADASTRO datetime NOT NULL,
  PRECO decimal(5,2) DEFAULT NULL,
  ID_IDIOMA int(11) NOT NULL,
  CODIGO_ISBN varchar(13) NOT NULL,
  EDICAO int(3) NOT NULL,
  ANO int(4) DEFAULT NULL,
  PAGINAS int(4) DEFAULT NULL,
  VIDEO tinyint(1) NOT NULL,
  CD_DVD tinyint(1) NOT NULL,
  E_BOOK tinyint(1) DEFAULT NULL,
  BROCHURA tinyint(1) DEFAULT NULL,
  DESCRICAO text,
  ID_EDITORA int(11) NOT NULL,
  EXCLUIDO tinyint(1) DEFAULT NULL,
  REVISTA tinyint(1) NOT NULL,
  PRIMARY KEY (`ID_LIVRO`),
  UNIQUE KEY `CODISBN_UNIQUE` (`CODIGO_ISBN`),
  UNIQUE KEY `ID_IDIOMA_UNIQUE` (`ID_IDIOMA`),
  KEY `fk_TB_IDIOMA_idx` (`ID_IDIOMA`),
  KEY `fk_TB_EDITORA_idx` (`ID_EDITORA`),
  CONSTRAINT `fk_TB_EDITORA` FOREIGN KEY (`ID_EDITORA`) REFERENCES `TB_EDITORA` (`ID_EDITORA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_IDIOMA` FOREIGN KEY (`ID_IDIOMA`) REFERENCES `TB_IDIOMA` (`ID_IDIOMA`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE TB_LIVRO_AUTOR (
  ID_LIVRO int(11) NOT NULL,
  ID_AUTOR int(11) NOT NULL,
  KEY fk_livro_idx (id_livro),
  KEY fk_autor (id_autor),
  CONSTRAINT fk_autor FOREIGN KEY (id_autor) REFERENCES TB_AUTOR (id_autor) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT fk_livro FOREIGN KEY (id_livro) REFERENCES TB_LIVRO (ID_LIVRO) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_MARCA (
  ID_MARCA int(11) NOT NULL AUTO_INCREMENT,
  NOME varchar(255) NOT NULL,
  PRIMARY KEY (ID_MARCA)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_EQUIPAMENTOS (
  ID_EQUIPAMENTO int(11) NOT NULL AUTO_INCREMENT,
  N_PATRIMONIO int(13) NOT NULL,
  STATUS tinyint(1) NOT NULL,
  MODELO varchar(120) DEFAULT NULL,
  VALOR_AQUISICAO decimal(9,2) DEFAULT NULL,
  DATA_CADASTRO datetime NOT NULL,
  OBSERVACAO text,
  ID_MARCA int(11) NOT NULL,
  ID_PROJETO int(11) NOT NULL,
  PRIMARY KEY (`ID_EQUIPAMENTO`),
  UNIQUE KEY `n_patrimonio_UNIQUE` (`N_PATRIMONIO`),
  UNIQUE KEY `ID_PROJETO_UNIQUE` (`ID_PROJETO`),
  UNIQUE KEY `ID_MARCA_UNIQUE` (`ID_MARCA`),
  KEY `FK_ID_MARCA_idx` (`ID_MARCA`),
  CONSTRAINT `FK_ID_MARCA` FOREIGN KEY (`ID_MARCA`) REFERENCES `TB_MARCA` (`ID_MARCA`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_ID_PROJETO` FOREIGN KEY (`ID_PROJETO`) REFERENCES `TB_PROJETOS` (`ID_PROJETO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_COMPUTADOR (
  ID_COMPUTADOR int(11) NOT NULL,
  TIPO_COMPUTADOR varchar(120) NOT NULL,
  ID_EQUIPAMENTO int(11) NOT NULL,
  PRIMARY KEY (`ID_COMPUTADOR`),
  UNIQUE KEY `ID_EQUIPAMENTO_UNIQUE` (`ID_EQUIPAMENTO`),
  CONSTRAINT `FK_ID_EQUIPAMENTO` FOREIGN KEY (`ID_EQUIPAMENTO`) REFERENCES `TB_EQUIPAMENTOS` (`ID_EQUIPAMENTO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE TB_MOBILE (
  ID_MOBILE int(11) NOT NULL AUTO_INCREMENT,
  TIPO_EQUIPAMENTO varchar(120) NOT NULL,
  ID_EQUIPAMENTO int(11) NOT NULL,
  PRIMARY KEY (`ID_MOBILE`),
  KEY `FK_ID_EQUIP_MOVEL_idx` (`ID_EQUIPAMENTO`),
  CONSTRAINT `FK_ID_EQUIP_MOVEL` FOREIGN KEY (`ID_EQUIPAMENTO`) REFERENCES `TB_EQUIPAMENTOS` (`ID_EQUIPAMENTO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE TB_PERIFERICO (
  ID_PERIFERICO int(11) NOT NULL AUTO_INCREMENT,
  TIPO_PERIFERICO varchar(120) NOT NULL,
  ID_EQUIPAMENTO int(11) NOT NULL,
  PRIMARY KEY (`ID_PERIFERICO`),
  KEY `FK_ID_EQUIPAMENTO_idx` (`ID_EQUIPAMENTO`),
  CONSTRAINT `FK_ID_EQUIP_PERI` FOREIGN KEY (`ID_EQUIPAMENTO`) REFERENCES `TB_EQUIPAMENTOS` (`ID_EQUIPAMENTO`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE OR REPLACE VIEW VW_EQUIPAMENTOS AS
SELECT 
if(Id_Mobile is not null, 'Dispositivo Movel', 
  if(Id_Computador is not null, 'Computador', 'Periferico')
) as Tipo_Equipamento,
if(Id_Mobile is not null, Tipo_Mobile, 
  if(Id_Computador is not null, TIPO_COMPUTADOR, TIPO_PERIFERICO)
) as Sub_Tipo,
Id_Mobile, Id_Computador, Id_Periferico, N_Patrimonio, Data_Cadastro, Valor_Aquisicao, MAR.Nome, Modelo
FROM 
TB_EQUIPAMENTOS as EQUIP
left join TB_COMPUTADOR as COMP on COMP.ID_EQUIPAMENTO = EQUIP.ID_EQUIPAMENTO
left join TB_PERIFERICO as PERIF on PERIF.ID_EQUIPAMENTO = EQUIP.ID_EQUIPAMENTO
left join TB_MOBILE AS MOB on MOB.ID_EQUIPAMENTO = EQUIP.ID_EQUIPAMENTO
inner join TB_MARCA as MAR on MAR.ID_MARCA = EQUIP.ID_MARCA;

/*Vinicius - Precisei fazer essas mudancas no banco. Do contrario nao consigo inserir mais de
um equipamento em um mesmo projeto*/
alter table TB_EQUIPAMENTOS drop foreign key FK_ID_PROJETO;
ALTER TABLE TB_EQUIPAMENTOS DROP INDEX ID_PROJETO_UNIQUE;
alter table TB_EQUIPAMENTOS drop foreign key FK_ID_MARCA;
ALTER TABLE TB_EQUIPAMENTOS DROP INDEX ID_MARCA_UNIQUE;
alter table TB_MOBILE change Tipo_Equipamento Tipo_Mobile VARCHAR(120);

/* SCRIPTS DE INSERCAO PRA FACILITAR TESTES */
INSERT INTO TB_FUNCAO
(ID_FUNCAO, NOME, DESCRICAO)
VALUES
('1', 'PROF', 'PROF DA PUC');

INSERT INTO TB_USUARIO
(ID_USUARIO,USUARIO,SENHA,ADMINISTRADOR,MATRICULA,NOME,EMAIL,DATA_CADASTRO, ID_FUNCAO, CPF)
VALUES
('10', 'admin', 'admin', '1', '00000', 'Cassio Trindade', 'cassio.trindade@pucrs.br', '2015-10-01 00:00:00', '1', '12345789999');

INSERT INTO TB_IDIOMA
(ID_IDIOMA, PAIS, NOME)
VALUES
(1, 'BRASIL', 'PORTUGUES');

INSERT INTO TB_AUTOR
(ID_AUTOR,NOME,SOBRENOME)
VALUES
( 1, 'Paulo', 'Coelho');

INSERT INTO TB_EDITORA
(ID_EDITORA,NOME)
VALUES
( 1, 'Abril');

INSERT INTO TB_EDITORA
(ID_EDITORA,NOME)
VALUES
( 2, 'Saraiva');

INSERT INTO TB_LIVRO
(ID_LIVRO,TITULO,SUBTITULO,DATA_CADASTRO,ID_IDIOMA,CODIGO_ISBN,EDICAO, ANO, PAGINAS, VIDEO, CD_DVD, E_BOOK, BROCHURA, DESCRICAO, ID_EDITORA, EXCLUIDO, REVISTA)
VALUES
( 1, 'A arte da guerra', '--', '2015-10-01 00:00:00', 1, 111111111111, 1, 1990, 100, 1, 0, 1, 1, 'NOVO LIVRO', 2, 0, 0);

INSERT INTO TB_LIVRO_AUTOR
(ID_LIVRO,ID_AUTOR)
VALUES
(1, 1);

INSERT INTO TB_LIVRO_AUTOR
(ID_LIVRO,ID_AUTOR)
VALUES
(1, 1);

INSERT INTO TB_MARCA
(ID_MARCA, NOME)
VALUES
(1, 'SAMSUNG');

insert into TB_PROJETOS
(Id_Projeto, Nome_Projeto, Programa, Origem, Data_Cadastro, Id_Cordenador)
values
(1, "Projeto Teste", "Desenvolvimento AGES", "TESTES", "2016-04-05", 10);

insert into TB_EQUIPAMENTOS
(Id_Equipamento, N_Patrimonio, Status, Modelo, 
Valor_Aquisicao, Data_Cadastro, Observacao, Id_Marca, Id_Projeto)
VALUES
(1, 123, 1, "Inspiron 15R", 
2500, '2016-04-05', "Observacao 1", 1, 1);

insert into TB_EQUIPAMENTOS
(Id_Equipamento, N_Patrimonio, Status, Modelo, 
Valor_Aquisicao, Data_Cadastro, Observacao, Id_Marca, Id_Projeto)
VALUES
(2, 456, 1, "HP", 
1000, '2016-04-05', "Observacao 2", 1, 1);

insert into TB_EQUIPAMENTOS
(Id_Equipamento, N_Patrimonio, Status, Modelo, 
Valor_Aquisicao, Data_Cadastro, Observacao, Id_Marca, Id_Projeto)
VALUES
(3, 789, 1, "Galaxy", 
750, '2016-04-05', "Observacao 3", 1, 1);

insert into TB_COMPUTADOR
(Id_Computador, Tipo_Computador, Id_Equipamento)
values
(1, "Notebook", 1);

insert into TB_PERIFERICO
(Id_Periferico, Tipo_Periferico, Id_Equipamento)
values
(1, "Impressora", 2);

insert into TB_MOBILE
(Id_Mobile, Tipo_Mobile, Id_Equipamento)
values
(1, "Celular", 3);
